### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by bingtong109** [grasses/PoisonPrompt#1]
Hi~ I got a ModuleNotFoundError when I ran the **step1_attack.py**. It reminds me that there is no module named '**datasets**'. Could you tell me how could I get this module?

**Comment by ZJU-ccc** [comment]
> Hi~ I got a ModuleNotFoundError when I ran the **step1_attack.py**. It reminds me that there is no module named '**datasets**'. Could you tell me how could I get this module?

you can try 'pip install datasets' in the terminal

**Comment by grasses** [comment]
pip install datasets
